// ClearCast - Tactical Forecast Management
// Gusto Customer Care WFM Tool
// Real data from Google Sheets exports
// Last updated: 2026-03-25
// MTD Period: March 1-23, 2026 (forecast and actuals for variance)
// Weekly Forecast: Mar 28 - Apr 3, 2026 (from CT Forecast Daily CSVs)

export const forecastGroups = [
  // ============================================
  // SALES (MTD from SMB Actuals, Weekly from SMB CT Forecast Daily)
  // ============================================
  {
    id: 500,
    name: 'Sales - Inbound',
    category: 'Sales',
    channel: 'Phone',
    forecastVolume: 5589,
    actualVolume: 5078,
    forecastAHT: 445,
    actualAHT: 442,
    weeklyForecastVolume: 1559,
    weeklyForecastAHT: 445,
    serviceLevel: 77,
    slTarget: 80,
    weeklyTrend: 4.6,
  },
  {
    id: 550,
    name: 'Sales - Email',
    category: 'Sales',
    channel: 'Email',
    forecastVolume: 1526,
    actualVolume: 230,
    forecastAHT: 600,
    actualAHT: 0,
    weeklyForecastVolume: 74,
    weeklyForecastAHT: 0,
    serviceLevel: 0,
    slTarget: 90,
    weeklyTrend: -14.7,
  },
  {
    id: 560,
    name: 'Sales - Chat',
    category: 'Sales',
    channel: 'Chat',
    forecastVolume: 2722,
    actualVolume: 1564,
    forecastAHT: 568,
    actualAHT: 547,
    weeklyForecastVolume: 524,
    weeklyForecastAHT: 568,
    serviceLevel: 54,
    slTarget: 80,
    weeklyTrend: -25.1,
  },
  {
    id: 600,
    name: 'Sales - Outbound',
    category: 'Sales',
    channel: 'Phone',
    forecastVolume: 27342,
    actualVolume: 28457,
    forecastAHT: 145,
    actualAHT: 147,
    weeklyForecastVolume: 8922,
    weeklyForecastAHT: 145,
    serviceLevel: 0,
    slTarget: 85,
    weeklyTrend: 0.2,
  },

  // ============================================
  // GPC SALES (MTD from SMB Actuals, Weekly from SMB CT Forecast Daily)
  // ============================================
  {
    id: 610,
    name: 'GPC Sales - Inbound',
    category: 'GPC Sales',
    channel: 'Phone',
    forecastVolume: 379,
    actualVolume: 158,
    forecastAHT: 387,
    actualAHT: 406,
    weeklyForecastVolume: 48,
    weeklyForecastAHT: 387,
    serviceLevel: 71,
    slTarget: 80,
    weeklyTrend: -15.7,
  },

  // ============================================
  // ONBOARDING (MTD from SMB Actuals, Weekly from SMB CT Forecast Daily)
  // ============================================
  {
    id: 501,
    name: 'Onboarding - Inbound',
    category: 'Onboarding',
    channel: 'Phone',
    forecastVolume: 6093,
    actualVolume: 6498,
    forecastAHT: 696,
    actualAHT: 698,
    weeklyForecastVolume: 2002,
    weeklyForecastAHT: 696,
    serviceLevel: 82,
    slTarget: 85,
    weeklyTrend: 15.6,
  },
  {
    id: 561,
    name: 'Onboarding - Chat',
    category: 'Onboarding',
    channel: 'Chat',
    forecastVolume: 1328,
    actualVolume: 1857,
    forecastAHT: 898,
    actualAHT: 860,
    weeklyForecastVolume: 619,
    weeklyForecastAHT: 898,
    serviceLevel: 14,
    slTarget: 80,
    weeklyTrend: -18.5,
  },
  {
    id: 601,
    name: 'Onboarding - Outbound',
    category: 'Onboarding',
    channel: 'Phone',
    forecastVolume: 12257,
    actualVolume: 15374,
    forecastAHT: 87,
    actualAHT: 85,
    weeklyForecastVolume: 4753,
    weeklyForecastAHT: 87,
    serviceLevel: 0,
    slTarget: 85,
    weeklyTrend: -6.3,
  },

  // ============================================
  // MONEY (MTD from Customer Care Actuals)
  // ============================================
  {
    id: 710,
    name: 'Money - Phone',
    category: 'Money',
    channel: 'Phone',
    forecastVolume: 4636,
    actualVolume: 4317,
    forecastAHT: 695,
    actualAHT: 492,
    weeklyForecastVolume: 1390,
    weeklyForecastAHT: 699,
    serviceLevel: 66,
    slTarget: 80,
    weeklyTrend: -6.4,
  },
  {
    id: 720,
    name: 'Money - Email',
    category: 'Money',
    channel: 'Email',
    forecastVolume: 2928,
    actualVolume: 3123,
    forecastAHT: 700,
    actualAHT: 721,
    weeklyForecastVolume: 1468,
    weeklyForecastAHT: 702,
    serviceLevel: 74,
    slTarget: 90,
    weeklyTrend: -3.2,
  },
  {
    id: 725,
    name: 'Money T1 Premium - Email',
    category: 'Money',
    channel: 'Email',
    forecastVolume: 1094,
    actualVolume: 1106,
    forecastAHT: 750,
    actualAHT: 778,
    weeklyForecastVolume: 521,
    weeklyForecastAHT: 759,
    serviceLevel: 83,
    slTarget: 95,
    weeklyTrend: -14.3,
  },
  {
    id: 730,
    name: 'Money - Chat',
    category: 'Money',
    channel: 'Chat',
    forecastVolume: 1938,
    actualVolume: 2074,
    forecastAHT: 764,
    actualAHT: 776,
    weeklyForecastVolume: 623,
    weeklyForecastAHT: 764,
    serviceLevel: 87,
    slTarget: 80,
    weeklyTrend: -44.8,
  },
  {
    id: 735,
    name: 'Money T1 Premium - Chat',
    category: 'Money',
    channel: 'Chat',
    forecastVolume: 543,
    actualVolume: 624,
    forecastAHT: 807,
    actualAHT: 817,
    weeklyForecastVolume: 189,
    weeklyForecastAHT: 803,
    serviceLevel: 84,
    slTarget: 95,
    weeklyTrend: -31.2,
  },

  // ============================================
  // MONEY T2 (MTD from Customer Care Actuals)
  // ============================================
  {
    id: 721,
    name: 'Money T2 - Email',
    category: 'Money T2',
    channel: 'Email',
    forecastVolume: 3476,
    actualVolume: 4135,
    forecastAHT: 1095,
    actualAHT: 1171,
    weeklyForecastVolume: 1241,
    weeklyForecastAHT: 1012,
    serviceLevel: 52,
    slTarget: 90,
    weeklyTrend: -2.9,
  },
  {
    id: 726,
    name: 'Money T2 Premium - Email',
    category: 'Money T2',
    channel: 'Email',
    forecastVolume: 1012,
    actualVolume: 1210,
    forecastAHT: 871,
    actualAHT: 840,
    weeklyForecastVolume: 356,
    weeklyForecastAHT: 928,
    serviceLevel: 71,
    slTarget: 95,
    weeklyTrend: 8.3,
  },

  // ============================================
  // PAYROLL/TAXES (MTD from Customer Care Actuals)
  // ============================================
  {
    id: 10110,
    name: 'Care Payroll/Taxes - Phone',
    category: 'Payroll/Taxes',
    channel: 'Phone',
    forecastVolume: 45577,
    actualVolume: 44209,
    forecastAHT: 940,
    actualAHT: 655,
    weeklyForecastVolume: 14798,
    weeklyForecastAHT: 940,
    serviceLevel: 74,
    slTarget: 80,
    weeklyTrend: -16.5,
  },
  {
    id: 10210,
    name: 'Care Payroll/Taxes - Email',
    category: 'Payroll/Taxes',
    channel: 'Email',
    forecastVolume: 8309,
    actualVolume: 8389,
    forecastAHT: 1530,
    actualAHT: 1602,
    weeklyForecastVolume: 2594,
    weeklyForecastAHT: 1508,
    serviceLevel: 68,
    slTarget: 90,
    weeklyTrend: -17.8,
  },
  {
    id: 10212,
    name: 'Care Payroll/Taxes Micro - Email',
    category: 'Payroll/Taxes',
    channel: 'Email',
    forecastVolume: 6075,
    actualVolume: 6425,
    forecastAHT: 1299,
    actualAHT: 1335,
    weeklyForecastVolume: 1983,
    weeklyForecastAHT: 1214,
    serviceLevel: 70,
    slTarget: 90,
    weeklyTrend: -22.3,
  },
  {
    id: 10215,
    name: 'Care Payroll/Taxes Premium - Email',
    category: 'Payroll/Taxes',
    channel: 'Email',
    forecastVolume: 6951,
    actualVolume: 6546,
    forecastAHT: 1545,
    actualAHT: 1553,
    weeklyForecastVolume: 2052,
    weeklyForecastAHT: 1605,
    serviceLevel: 69,
    slTarget: 95,
    weeklyTrend: 1.3,
  },
  {
    id: 10217,
    name: 'Care Payroll/Taxes Micro Premium - Email',
    category: 'Payroll/Taxes',
    channel: 'Email',
    forecastVolume: 1531,
    actualVolume: 1667,
    forecastAHT: 1438,
    actualAHT: 1413,
    weeklyForecastVolume: 510,
    weeklyForecastAHT: 1283,
    serviceLevel: 72,
    slTarget: 95,
    weeklyTrend: -10.5,
  },
  {
    id: 10311,
    name: 'Care Payroll/Taxes - Chat',
    category: 'Payroll/Taxes',
    channel: 'Chat',
    forecastVolume: 7983,
    actualVolume: 7470,
    forecastAHT: 1114,
    actualAHT: 1128,
    weeklyForecastVolume: 2544,
    weeklyForecastAHT: 1108,
    serviceLevel: 79,
    slTarget: 80,
    weeklyTrend: -11.9,
  },
  {
    id: 10312,
    name: 'Care Payroll/Taxes Micro - Chat',
    category: 'Payroll/Taxes',
    channel: 'Chat',
    forecastVolume: 6301,
    actualVolume: 6376,
    forecastAHT: 1155,
    actualAHT: 1171,
    weeklyForecastVolume: 2144,
    weeklyForecastAHT: 1149,
    serviceLevel: 80,
    slTarget: 80,
    weeklyTrend: -13.9,
  },
  {
    id: 10315,
    name: 'Care Payroll/Taxes Premium - Chat',
    category: 'Payroll/Taxes',
    channel: 'Chat',
    forecastVolume: 2349,
    actualVolume: 2410,
    forecastAHT: 1115,
    actualAHT: 1127,
    weeklyForecastVolume: 815,
    weeklyForecastAHT: 1089,
    serviceLevel: 84,
    slTarget: 95,
    weeklyTrend: 0.3,
  },
  {
    id: 10317,
    name: 'Care Payroll/Taxes Micro Premium - Chat',
    category: 'Payroll/Taxes',
    channel: 'Chat',
    forecastVolume: 871,
    actualVolume: 975,
    forecastAHT: 1092,
    actualAHT: 1135,
    weeklyForecastVolume: 328,
    weeklyForecastAHT: 1074,
    serviceLevel: 84,
    slTarget: 95,
    weeklyTrend: -2.1,
  },
  {
    id: 30112,
    name: 'Care Accountant Bronze - Phone',
    category: 'Payroll/Taxes',
    channel: 'Phone',
    forecastVolume: 1892,
    actualVolume: 1826,
    forecastAHT: 808,
    actualAHT: 568,
    weeklyForecastVolume: 615,
    weeklyForecastAHT: 807,
    serviceLevel: 74,
    slTarget: 80,
    weeklyTrend: -27.0,
  },
  {
    id: 30113,
    name: 'Care Accountant Starter - Phone',
    category: 'Payroll/Taxes',
    channel: 'Phone',
    forecastVolume: 3113,
    actualVolume: 2912,
    forecastAHT: 836,
    actualAHT: 575,
    weeklyForecastVolume: 978,
    weeklyForecastAHT: 836,
    serviceLevel: 73,
    slTarget: 80,
    weeklyTrend: -9.6,
  },
  {
    id: 30311,
    name: 'Care Accountants Payroll/Taxes - Chat',
    category: 'Payroll/Taxes',
    channel: 'Chat',
    forecastVolume: 3995,
    actualVolume: 3884,
    forecastAHT: 1204,
    actualAHT: 1234,
    weeklyForecastVolume: 1313,
    weeklyForecastAHT: 1158,
    serviceLevel: 81,
    slTarget: 80,
    weeklyTrend: -17.9,
  },
  {
    id: 40110,
    name: 'Care Client Relations - Phone',
    category: 'Payroll/Taxes',
    channel: 'Phone',
    forecastVolume: 414,
    actualVolume: 387,
    forecastAHT: 727,
    actualAHT: 521,
    weeklyForecastVolume: 131,
    weeklyForecastAHT: 723,
    serviceLevel: 74,
    slTarget: 80,
    weeklyTrend: -44.9,
  },

  // ============================================
  // PREMIER (MTD from Customer Care Actuals)
  // ============================================
  {
    id: 20110,
    name: 'Care Premier - Phone',
    category: 'Premier',
    channel: 'Phone',
    forecastVolume: 3684,
    actualVolume: 3654,
    forecastAHT: 791,
    actualAHT: 554,
    weeklyForecastVolume: 1246,
    weeklyForecastAHT: 793,
    serviceLevel: 60,
    slTarget: 90,
    weeklyTrend: -3.0,
  },
  {
    id: 20120,
    name: 'Care Gusto Global - Phone',
    category: 'Premier',
    channel: 'Phone',
    forecastVolume: 19,
    actualVolume: 22,
    forecastAHT: 645,
    actualAHT: 175,
    weeklyForecastVolume: 7,
    weeklyForecastAHT: 631,
    serviceLevel: 47,
    slTarget: 90,
    weeklyTrend: 60.0,
  },
  {
    id: 20211,
    name: 'Care Payroll/Taxes Grow50 - Email',
    category: 'Premier',
    channel: 'Email',
    forecastVolume: 498,
    actualVolume: 430,
    forecastAHT: 2133,
    actualAHT: 2125,
    weeklyForecastVolume: 147,
    weeklyForecastAHT: 1692,
    serviceLevel: 72,
    slTarget: 90,
    weeklyTrend: 5.0,
  },
  {
    id: 20216,
    name: 'Care Payroll/Taxes Grow50 Premium - Email',
    category: 'Premier',
    channel: 'Email',
    forecastVolume: 1515,
    actualVolume: 1420,
    forecastAHT: 2508,
    actualAHT: 1979,
    weeklyForecastVolume: 476,
    weeklyForecastAHT: 2433,
    serviceLevel: 72,
    slTarget: 95,
    weeklyTrend: -12.0,
  },
  {
    id: 20220,
    name: 'Care Gusto Global - Email',
    category: 'Premier',
    channel: 'Email',
    forecastVolume: 910,
    actualVolume: 700,
    forecastAHT: 1710,
    actualAHT: 1932,
    weeklyForecastVolume: 245,
    weeklyForecastAHT: 1480,
    serviceLevel: 57,
    slTarget: 90,
    weeklyTrend: -21.4,
  },
  {
    id: 20225,
    name: 'Care Gusto Global Premium - Email',
    category: 'Premier',
    channel: 'Email',
    forecastVolume: 234,
    actualVolume: 258,
    forecastAHT: 2027,
    actualAHT: 1456,
    weeklyForecastVolume: 85,
    weeklyForecastAHT: 1644,
    serviceLevel: 66,
    slTarget: 95,
    weeklyTrend: -6.3,
  },
  {
    id: 20311,
    name: 'Care Payroll/Taxes Grow50 - Chat',
    category: 'Premier',
    channel: 'Chat',
    forecastVolume: 593,
    actualVolume: 539,
    forecastAHT: 1182,
    actualAHT: 1036,
    weeklyForecastVolume: 166,
    weeklyForecastAHT: 1070,
    serviceLevel: 83,
    slTarget: 85,
    weeklyTrend: 3.6,
  },
  {
    id: 20316,
    name: 'Care Payroll/Taxes Grow50 Premium - Chat',
    category: 'Premier',
    channel: 'Chat',
    forecastVolume: 441,
    actualVolume: 438,
    forecastAHT: 944,
    actualAHT: 793,
    weeklyForecastVolume: 144,
    weeklyForecastAHT: 936,
    serviceLevel: 85,
    slTarget: 95,
    weeklyTrend: -18.8,
  },
  {
    id: 20420,
    name: 'Care Gusto Global - Chat',
    category: 'Premier',
    channel: 'Chat',
    forecastVolume: 84,
    actualVolume: 77,
    forecastAHT: 1264,
    actualAHT: 909,
    weeklyForecastVolume: 25,
    weeklyForecastAHT: 1278,
    serviceLevel: 72,
    slTarget: 85,
    weeklyTrend: -22.2,
  },
  {
    id: 20425,
    name: 'Care Gusto Global Premium - Chat',
    category: 'Premier',
    channel: 'Chat',
    forecastVolume: 17,
    actualVolume: 13,
    forecastAHT: 1541,
    actualAHT: 717,
    weeklyForecastVolume: 5,
    weeklyForecastAHT: 1604,
    serviceLevel: 70,
    slTarget: 95,
    weeklyTrend: 0.0,
  },

  // ============================================
  // BENEFITS (MTD from Customer Care Actuals)
  // ============================================
  {
    id: 20210,
    name: 'Care Benefits Grow50 - Email',
    category: 'Benefits',
    channel: 'Email',
    forecastVolume: 0,
    actualVolume: 121,
    forecastAHT: 1399,
    actualAHT: 1541,
    weeklyForecastVolume: 0,
    weeklyForecastAHT: 1399,
    serviceLevel: 71,
    slTarget: 90,
    weeklyTrend: 0.0,
  },
  {
    id: 20215,
    name: 'Care Benefits Grow50 Premium - Email',
    category: 'Benefits',
    channel: 'Email',
    forecastVolume: 0,
    actualVolume: 379,
    forecastAHT: 1130,
    actualAHT: 1238,
    weeklyForecastVolume: 0,
    weeklyForecastAHT: 1130,
    serviceLevel: 72,
    slTarget: 95,
    weeklyTrend: 0.0,
  },
  {
    id: 20310,
    name: 'Care Benefits Grow50 - Chat',
    category: 'Benefits',
    channel: 'Chat',
    forecastVolume: 0,
    actualVolume: 242,
    forecastAHT: 648,
    actualAHT: 572,
    weeklyForecastVolume: 0,
    weeklyForecastAHT: 648,
    serviceLevel: 82,
    slTarget: 85,
    weeklyTrend: 0.0,
  },
  {
    id: 20315,
    name: 'Care Benefits Grow50 Premium - Chat',
    category: 'Benefits',
    channel: 'Chat',
    forecastVolume: 0,
    actualVolume: 126,
    forecastAHT: 1123,
    actualAHT: 695,
    weeklyForecastVolume: 0,
    weeklyForecastAHT: 1123,
    serviceLevel: 83,
    slTarget: 95,
    weeklyTrend: 0.0,
  },
  {
    id: 50110,
    name: 'Care Benefits - Phone',
    category: 'Benefits',
    channel: 'Phone',
    forecastVolume: 12723,
    actualVolume: 11062,
    forecastAHT: 803,
    actualAHT: 558,
    weeklyForecastVolume: 3252,
    weeklyForecastAHT: 801,
    serviceLevel: 60,
    slTarget: 80,
    weeklyTrend: -18.7,
  },
  {
    id: 50210,
    name: 'Care Benefits - Email',
    category: 'Benefits',
    channel: 'Email',
    forecastVolume: 1998,
    actualVolume: 2090,
    forecastAHT: 1740,
    actualAHT: 1729,
    weeklyForecastVolume: 645,
    weeklyForecastAHT: 1707,
    serviceLevel: 69,
    slTarget: 90,
    weeklyTrend: 3.2,
  },
  {
    id: 50211,
    name: 'Care Benefits Admin - Email',
    category: 'Benefits',
    channel: 'Email',
    forecastVolume: 3224,
    actualVolume: 3067,
    forecastAHT: 1876,
    actualAHT: 1964,
    weeklyForecastVolume: 908,
    weeklyForecastAHT: 1816,
    serviceLevel: 78,
    slTarget: 90,
    weeklyTrend: -1.7,
  },
  {
    id: 50215,
    name: 'Care Benefits Premium - Email',
    category: 'Benefits',
    channel: 'Email',
    forecastVolume: 384,
    actualVolume: 314,
    forecastAHT: 1541,
    actualAHT: 1607,
    weeklyForecastVolume: 209,
    weeklyForecastAHT: 1632,
    serviceLevel: 90,
    slTarget: 95,
    weeklyTrend: -13.4,
  },
  {
    id: 50216,
    name: 'Care Benefits Admin Premium - Email',
    category: 'Benefits',
    channel: 'Email',
    forecastVolume: 2330,
    actualVolume: 2317,
    forecastAHT: 2280,
    actualAHT: 2290,
    weeklyForecastVolume: 685,
    weeklyForecastAHT: 1940,
    serviceLevel: 77,
    slTarget: 95,
    weeklyTrend: -16.9,
  },
  {
    id: 50310,
    name: 'Care Benefits - Chat',
    category: 'Benefits',
    channel: 'Chat',
    forecastVolume: 1948,
    actualVolume: 1977,
    forecastAHT: 708,
    actualAHT: 766,
    weeklyForecastVolume: 715,
    weeklyForecastAHT: 700,
    serviceLevel: 86,
    slTarget: 80,
    weeklyTrend: -15.6,
  },
  {
    id: 50311,
    name: 'Care Benefits Admin - Chat',
    category: 'Benefits',
    channel: 'Chat',
    forecastVolume: 4644,
    actualVolume: 4428,
    forecastAHT: 674,
    actualAHT: 682,
    weeklyForecastVolume: 1462,
    weeklyForecastAHT: 671,
    serviceLevel: 83,
    slTarget: 80,
    weeklyTrend: -22.3,
  },
  {
    id: 50315,
    name: 'Care Benefits Premium - Chat',
    category: 'Benefits',
    channel: 'Chat',
    forecastVolume: 315,
    actualVolume: 360,
    forecastAHT: 810,
    actualAHT: 814,
    weeklyForecastVolume: 158,
    weeklyForecastAHT: 794,
    serviceLevel: 83,
    slTarget: 95,
    weeklyTrend: 5.2,
  },
  {
    id: 50316,
    name: 'Care Benefits Admin Premium - Chat',
    category: 'Benefits',
    channel: 'Chat',
    forecastVolume: 1013,
    actualVolume: 1031,
    forecastAHT: 666,
    actualAHT: 654,
    weeklyForecastVolume: 340,
    weeklyForecastAHT: 681,
    serviceLevel: 87,
    slTarget: 95,
    weeklyTrend: 4.3,
  },
  {
    id: 80210,
    name: 'Care Tada - Email',
    category: 'Benefits',
    channel: 'Email',
    forecastVolume: 299,
    actualVolume: 223,
    forecastAHT: 1743,
    actualAHT: 1709,
    weeklyForecastVolume: 63,
    weeklyForecastAHT: 1816,
    serviceLevel: 67,
    slTarget: 90,
    weeklyTrend: -23.8,
  },
  {
    id: 80211,
    name: 'Care Tada Grower - Email',
    category: 'Benefits',
    channel: 'Email',
    forecastVolume: 19,
    actualVolume: 33,
    forecastAHT: 1721,
    actualAHT: 1162,
    weeklyForecastVolume: 8,
    weeklyForecastAHT: 1900,
    serviceLevel: 44,
    slTarget: 90,
    weeklyTrend: 150.0,
  },
  {
    id: 80215,
    name: 'Care Tada Premium - Email',
    category: 'Benefits',
    channel: 'Email',
    forecastVolume: 69,
    actualVolume: 80,
    forecastAHT: 1820,
    actualAHT: 1599,
    weeklyForecastVolume: 25,
    weeklyForecastAHT: 1995,
    serviceLevel: 66,
    slTarget: 95,
    weeklyTrend: -10.0,
  },
  {
    id: 80310,
    name: 'Care Tada - Chat',
    category: 'Benefits',
    channel: 'Chat',
    forecastVolume: 228,
    actualVolume: 182,
    forecastAHT: 1021,
    actualAHT: 846,
    weeklyForecastVolume: 59,
    weeklyForecastAHT: 917,
    serviceLevel: 67,
    slTarget: 80,
    weeklyTrend: 0.0,
  },
  {
    id: 80311,
    name: 'Care Tada Grower - Chat',
    category: 'Benefits',
    channel: 'Chat',
    forecastVolume: 18,
    actualVolume: 13,
    forecastAHT: 765,
    actualAHT: 279,
    weeklyForecastVolume: 5,
    weeklyForecastAHT: 896,
    serviceLevel: 28,
    slTarget: 80,
    weeklyTrend: -50.0,
  },
  {
    id: 80315,
    name: 'Care Tada Premium - Chat',
    category: 'Benefits',
    channel: 'Chat',
    forecastVolume: 118,
    actualVolume: 100,
    forecastAHT: 988,
    actualAHT: 847,
    weeklyForecastVolume: 32,
    weeklyForecastAHT: 1059,
    serviceLevel: 57,
    slTarget: 95,
    weeklyTrend: 19.2,
  },
  {
    id: 80316,
    name: 'Care Tada Grower Premium - Chat',
    category: 'Benefits',
    channel: 'Chat',
    forecastVolume: 10,
    actualVolume: 7,
    forecastAHT: 762,
    actualAHT: 260,
    weeklyForecastVolume: 2,
    weeklyForecastAHT: 918,
    serviceLevel: 28,
    slTarget: 95,
    weeklyTrend: -25.0,
  },

  // ============================================
  // ACCOUNTANT (MTD from Customer Care Actuals)
  // ============================================
  {
    id: 30111,
    name: 'Care Accountant Silver/Gold - Phone',
    category: 'Accountant',
    channel: 'Phone',
    forecastVolume: 4154,
    actualVolume: 3834,
    forecastAHT: 805,
    actualAHT: 560,
    weeklyForecastVolume: 1304,
    weeklyForecastAHT: 805,
    serviceLevel: 53,
    slTarget: 85,
    weeklyTrend: -19.5,
  },
  {
    id: 30210,
    name: 'Care Accountants Payroll/Taxes - Email',
    category: 'Accountant',
    channel: 'Email',
    forecastVolume: 9371,
    actualVolume: 9166,
    forecastAHT: 1500,
    actualAHT: 1486,
    weeklyForecastVolume: 3087,
    weeklyForecastAHT: 1364,
    serviceLevel: 66,
    slTarget: 90,
    weeklyTrend: -13.3,
  },

  // ============================================
  // MEMBER (MTD from Customer Care Actuals)
  // ============================================
  {
    id: 70110,
    name: 'Care Members Payroll - Phone',
    category: 'Member',
    channel: 'Phone',
    forecastVolume: 6401,
    actualVolume: 6239,
    forecastAHT: 682,
    actualAHT: 479,
    weeklyForecastVolume: 1967,
    weeklyForecastAHT: 682,
    serviceLevel: 56,
    slTarget: 80,
    weeklyTrend: 5.7,
  },
  {
    id: 70210,
    name: 'Care Members Payroll - Email',
    category: 'Member',
    channel: 'Email',
    forecastVolume: 2678,
    actualVolume: 2871,
    forecastAHT: 933,
    actualAHT: 958,
    weeklyForecastVolume: 1338,
    weeklyForecastAHT: 959,
    serviceLevel: 88,
    slTarget: 90,
    weeklyTrend: -18.2,
  },
  {
    id: 70215,
    name: 'Care Members Payroll Premium - Email',
    category: 'Member',
    channel: 'Email',
    forecastVolume: 1029,
    actualVolume: 1158,
    forecastAHT: 962,
    actualAHT: 1012,
    weeklyForecastVolume: 530,
    weeklyForecastAHT: 1031,
    serviceLevel: 88,
    slTarget: 95,
    weeklyTrend: 0.9,
  },
  {
    id: 70315,
    name: 'Care Members Payroll Premium - Chat',
    category: 'Member',
    channel: 'Chat',
    forecastVolume: 651,
    actualVolume: 767,
    forecastAHT: 822,
    actualAHT: 830,
    weeklyForecastVolume: 238,
    weeklyForecastAHT: 845,
    serviceLevel: 100,
    slTarget: 95,
    weeklyTrend: 8.5,
  },
  {
    id: 702310,
    name: 'Care Members Payroll - Chat',
    category: 'Member',
    channel: 'Chat',
    forecastVolume: 2548,
    actualVolume: 1928,
    forecastAHT: 810,
    actualAHT: 827,
    weeklyForecastVolume: 609,
    weeklyForecastAHT: 824,
    serviceLevel: 99,
    slTarget: 80,
    weeklyTrend: -16.7,
  },

  // ============================================
  // BAC (MTD from Customer Care Actuals)
  // ============================================
  {
    id: 90110,
    name: 'Care BAC - Phone',
    category: 'BAC',
    channel: 'Phone',
    forecastVolume: 332,
    actualVolume: 241,
    forecastAHT: 989,
    actualAHT: 508,
    weeklyForecastVolume: 0,
    weeklyForecastAHT: 989,
    serviceLevel: 54,
    slTarget: 85,
    weeklyTrend: -38.5,
  },
  {
    id: 90210,
    name: 'Care BAC - Email',
    category: 'BAC',
    channel: 'Email',
    forecastVolume: 4256,
    actualVolume: 4645,
    forecastAHT: 1902,
    actualAHT: 1880,
    weeklyForecastVolume: 1335,
    weeklyForecastAHT: 1899,
    serviceLevel: 62,
    slTarget: 90,
    weeklyTrend: -7.5,
  },
  {
    id: 90212,
    name: 'Care BAC Tada - Email',
    category: 'BAC',
    channel: 'Email',
    forecastVolume: 893,
    actualVolume: 778,
    forecastAHT: 1380,
    actualAHT: 1396,
    weeklyForecastVolume: 231,
    weeklyForecastAHT: 1390,
    serviceLevel: 57,
    slTarget: 90,
    weeklyTrend: -20.2,
  },
  {
    id: 90215,
    name: 'Care BAC Premium - Email',
    category: 'BAC',
    channel: 'Email',
    forecastVolume: 1735,
    actualVolume: 1781,
    forecastAHT: 2494,
    actualAHT: 3425,
    weeklyForecastVolume: 524,
    weeklyForecastAHT: 1732,
    serviceLevel: 79,
    slTarget: 95,
    weeklyTrend: 0.4,
  },
  {
    id: 90217,
    name: 'Care BAC Tada Premium - Email',
    category: 'BAC',
    channel: 'Email',
    forecastVolume: 693,
    actualVolume: 681,
    forecastAHT: 1118,
    actualAHT: 1141,
    weeklyForecastVolume: 191,
    weeklyForecastAHT: 1100,
    serviceLevel: 87,
    slTarget: 95,
    weeklyTrend: -27.2,
  },
  {
    id: 90310,
    name: 'Care BAC - Chat',
    category: 'BAC',
    channel: 'Chat',
    forecastVolume: 270,
    actualVolume: 258,
    forecastAHT: 7570,
    actualAHT: 3022,
    weeklyForecastVolume: 88,
    weeklyForecastAHT: 1762,
    serviceLevel: 96,
    slTarget: 80,
    weeklyTrend: -22.4,
  },
  {
    id: 90315,
    name: 'Care BAC Premium - Chat',
    category: 'BAC',
    channel: 'Chat',
    forecastVolume: 48,
    actualVolume: 41,
    forecastAHT: 1224,
    actualAHT: 861,
    weeklyForecastVolume: 14,
    weeklyForecastAHT: 1106,
    serviceLevel: 85,
    slTarget: 95,
    weeklyTrend: -35.3,
  },

  // ============================================
  // PAC (MTD from Customer Care Actuals)
  // ============================================
  {
    id: 90111,
    name: 'Care PAC - Phone',
    category: 'PAC',
    channel: 'Phone',
    forecastVolume: 1811,
    actualVolume: 1683,
    forecastAHT: 1127,
    actualAHT: 794,
    weeklyForecastVolume: 554,
    weeklyForecastAHT: 1125,
    serviceLevel: 34,
    slTarget: 85,
    weeklyTrend: -14.8,
  },
  {
    id: 90211,
    name: 'Care PAC - Email',
    category: 'PAC',
    channel: 'Email',
    forecastVolume: 11449,
    actualVolume: 9871,
    forecastAHT: 2066,
    actualAHT: 2091,
    weeklyForecastVolume: 3350,
    weeklyForecastAHT: 2044,
    serviceLevel: 61,
    slTarget: 90,
    weeklyTrend: -9.7,
  },
  {
    id: 90216,
    name: 'Care PAC Premium - Email',
    category: 'PAC',
    channel: 'Email',
    forecastVolume: 2764,
    actualVolume: 2631,
    forecastAHT: 2299,
    actualAHT: 2740,
    weeklyForecastVolume: 894,
    weeklyForecastAHT: 2238,
    serviceLevel: 73,
    slTarget: 95,
    weeklyTrend: -18.7,
  },
  {
    id: 90311,
    name: 'Care PAC - Chat',
    category: 'PAC',
    channel: 'Chat',
    forecastVolume: 809,
    actualVolume: 754,
    forecastAHT: 1353,
    actualAHT: 1000,
    weeklyForecastVolume: 228,
    weeklyForecastAHT: 1223,
    serviceLevel: 67,
    slTarget: 80,
    weeklyTrend: -6.6,
  },
  {
    id: 90316,
    name: 'Care PAC Premium - Chat',
    category: 'PAC',
    channel: 'Chat',
    forecastVolume: 102,
    actualVolume: 124,
    forecastAHT: 1311,
    actualAHT: 889,
    weeklyForecastVolume: 40,
    weeklyForecastAHT: 1326,
    serviceLevel: 67,
    slTarget: 95,
    weeklyTrend: 24.2,
  },

  // ============================================
  // DSA (MTD from Customer Care Actuals)
  // ============================================
  {
    id: 90120,
    name: 'Care DSA Overflow - Phone',
    category: 'DSA',
    channel: 'Phone',
    forecastVolume: 3459,
    actualVolume: 4108,
    forecastAHT: 946,
    actualAHT: 656,
    weeklyForecastVolume: 1357,
    weeklyForecastAHT: 946,
    serviceLevel: 57,
    slTarget: 80,
    weeklyTrend: -14.9,
  },

  // ============================================
  // BENOPS (MTD from BenOps Actuals)
  // ============================================
  {
    id: 821,
    name: 'GroupOps - Submission',
    category: 'GroupOps',
    channel: 'Back Office',
    forecastVolume: 10052,
    actualVolume: 8491,
    forecastAHT: 1445,
    actualAHT: 1044,
    weeklyForecastVolume: 2691,
    weeklyForecastAHT: 1449,
    serviceLevel: 0,
    slTarget: 85,
    weeklyTrend: -5.0,
  },
  {
    id: 831,
    name: 'GroupOps - Confirmation',
    category: 'GroupOps',
    channel: 'Back Office',
    forecastVolume: 9591,
    actualVolume: 7999,
    forecastAHT: 2190,
    actualAHT: 1713,
    weeklyForecastVolume: 2474,
    weeklyForecastAHT: 2190,
    serviceLevel: 0,
    slTarget: 85,
    weeklyTrend: 7.4,
  },
  {
    id: 850,
    name: 'Benefit Transfers',
    category: 'Benefit Transfers',
    channel: 'Back Office',
    forecastVolume: 317,
    actualVolume: 165,
    forecastAHT: 5000,
    actualAHT: 5000,
    weeklyForecastVolume: 56,
    weeklyForecastAHT: 5000,
    serviceLevel: 0,
    slTarget: 80,
    weeklyTrend: 9.4,
  },
  {
    id: 860,
    name: 'BYB',
    category: 'BYB',
    channel: 'Back Office',
    forecastVolume: 740,
    actualVolume: 337,
    forecastAHT: 600,
    actualAHT: 600,
    weeklyForecastVolume: 73,
    weeklyForecastAHT: 600,
    serviceLevel: 0,
    slTarget: 85,
    weeklyTrend: -10.6,
  },
  {
    id: 870,
    name: 'BenOps Support',
    category: 'BenOps Support',
    channel: 'Back Office',
    forecastVolume: 2640,
    actualVolume: 2378,
    forecastAHT: 9432,
    actualAHT: 450,
    weeklyForecastVolume: 772,
    weeklyForecastAHT: 9432,
    serviceLevel: 0,
    slTarget: 85,
    weeklyTrend: 6.3,
  },
  {
    id: 950,
    name: 'Advising - Dedicated Advising',
    category: 'Advising',
    channel: 'Phone',
    forecastVolume: 2740,
    actualVolume: 112,
    forecastAHT: 4008,
    actualAHT: 3136,
    weeklyForecastVolume: 36,
    weeklyForecastAHT: 4008,
    serviceLevel: 0,
    slTarget: 80,
    weeklyTrend: -7.4,
  },
  {
    id: 970,
    name: 'Advising - Recerts and Packets',
    category: 'Advising',
    channel: 'Back Office',
    forecastVolume: 5283,
    actualVolume: 546,
    forecastAHT: 5648,
    actualAHT: 3823,
    weeklyForecastVolume: 85,
    weeklyForecastAHT: 5522,
    serviceLevel: 0,
    slTarget: 85,
    weeklyTrend: 7.9,
  },
  {
    id: 990,
    name: 'Advising - MYBC',
    category: 'Advising',
    channel: 'Phone',
    forecastVolume: 388,
    actualVolume: 74,
    forecastAHT: 7200,
    actualAHT: 4695,
    weeklyForecastVolume: 24,
    weeklyForecastAHT: 7200,
    serviceLevel: 0,
    slTarget: 80,
    weeklyTrend: 5.2,
  },
];

// Helper to calculate variance percentage
export const calcVariance = (forecast, actual) => {
  if (forecast === 0) return 0;
  return ((actual - forecast) / forecast * 100).toFixed(1);
};

// Get unique categories
export const categories = [...new Set(forecastGroups.map(g => g.category))];

// Get unique channels
export const channels = [...new Set(forecastGroups.map(g => g.channel))];

// Pillar groupings (high-level divisions)
export const pillars = {
  'Care': ['Payroll/Taxes', 'Benefits', 'Premier', 'Money', 'Money T2', 'Accountant', 'Member', 'BAC', 'PAC', 'DSA'],
  'Sales': ['Sales', 'GPC Sales', 'Onboarding'],
  'BenOps': ['GroupOps', 'Benefit Transfers', 'BYB', 'BenOps Support', 'Advising']
};

// Get pillar for a category
export const getPillarForCategory = (category) => {
  for (const [pillar, cats] of Object.entries(pillars)) {
    if (cats.includes(category)) return pillar;
  }
  return 'Other';
};

// Get all categories for a pillar
export const getCategoriesForPillar = (pillar) => {
  return pillars[pillar] || [];
};

// Get pillar summary stats
export const getPillarStats = (pillar, adjustments = {}, groups = []) => {
  const pillarCategories = pillars[pillar] || [];
  const pillarGroups = groups.filter(g => pillarCategories.includes(g.category));

  let totalVolume = 0;
  let totalForecast = 0;
  let volOnTargetCount = 0;
  let ahtOnTargetCount = 0;

  pillarGroups.forEach(group => {
    const adj = adjustments[group.id] || { volume: 0, aht: 0 };
    const adjForecast = group.forecastVolume * (1 + adj.volume / 100);
    const volVar = Math.abs((group.actualVolume - adjForecast) / adjForecast * 100);
    const ahtAdj = group.forecastAHT * (1 + adj.aht / 100);
    const ahtVar = Math.abs((group.actualAHT - ahtAdj) / ahtAdj * 100);

    totalVolume += group.actualVolume;
    totalForecast += adjForecast;
    if (volVar <= 5) volOnTargetCount++;
    if (ahtVar <= 5) ahtOnTargetCount++;
  });

  const n = pillarGroups.length;
  return {
    ctCount: n,
    totalVolume,
    totalForecast: Math.round(totalForecast),
    volOnTargetCount,
    ahtOnTargetCount,
    onTargetCount: volOnTargetCount, // kept for backwards compat (pillar badge uses vol)
    onTargetPct: n > 0 ? Math.round((volOnTargetCount / n) * 100) : 0,
    ahtOnTargetPct: n > 0 ? Math.round((ahtOnTargetCount / n) * 100) : 0,
  };
};

// Calculate projected volume for future weeks based on trend
// Uses weeklyForecastVolume as base (from CT Forecast Daily CSVs)
export const getProjectedVolume = (group, weeksOut = 1) => {
  const baseVolume = group.weeklyForecastVolume || group.forecastVolume;
  const trendMultiplier = 1 + (group.weeklyTrend / 100);
  return Math.round(baseVolume * Math.pow(trendMultiplier, weeksOut));
};

// Generate historical trend data for a group (last 8 weeks)
export const generateHistoricalData = (groupId, groups = []) => {
  const group = groups.find(g => g.id === groupId);
  if (!group) return [];

  const weeks = [];
  const today = new Date();

  for (let i = 7; i >= 0; i--) {
    const weekStart = new Date(today);
    weekStart.setDate(today.getDate() - (i * 7));
    const weekLabel = `Week of ${weekStart.toLocaleDateString('en-US', { month: 'short', day: 'numeric' })}`;

    const volumeVariance = 0.85 + Math.random() * 0.3;
    const ahtVariance = 0.9 + Math.random() * 0.2;
    const slVariance = -10 + Math.random() * 20;

    weeks.push({
      week: weekLabel,
      weekNumber: 8 - i,
      forecastVolume: Math.round(group.forecastVolume * (0.9 + Math.random() * 0.2)),
      actualVolume: i === 0 ? group.actualVolume : Math.round(group.forecastVolume * volumeVariance),
      forecastAHT: Math.round(group.forecastAHT * (0.95 + Math.random() * 0.1)),
      actualAHT: i === 0 ? group.actualAHT : Math.round(group.forecastAHT * ahtVariance),
      serviceLevel: i === 0 ? group.serviceLevel : Math.max(50, Math.min(99, group.serviceLevel + slVariance)),
      slTarget: group.slTarget,
    });
  }

  return weeks;
};

// Check if all groups are on target
export const checkAllOnTarget = (adjustments = {}, groups = []) => {
  return groups.every(group => {
    const adj = adjustments[group.id] || { volume: 0, aht: 0 };
    const adjustedForecast = group.forecastVolume * (1 + adj.volume / 100);
    const adjustedVariance = calcVariance(adjustedForecast, group.actualVolume);
    const ahtVariance = calcVariance(
      group.forecastAHT * (1 + adj.aht / 100),
      group.actualAHT
    );
    return Math.abs(parseFloat(adjustedVariance)) <= 5 && Math.abs(parseFloat(ahtVariance)) <= 5;
  });
};

// Get suggested adjustments to hit +/- 5% target
export const getSuggestedAdjustments = (groups = []) => {
  const suggestions = {};

  groups.forEach(group => {
    const volumeVar = parseFloat(calcVariance(group.forecastVolume, group.actualVolume));
    const ahtVar = parseFloat(calcVariance(group.forecastAHT, group.actualAHT));

    if (Math.abs(volumeVar) > 5 || Math.abs(ahtVar) > 5) {
      suggestions[group.id] = {
        volume: Math.abs(volumeVar) > 5 ? -Math.round(volumeVar) : 0,
        aht: Math.abs(ahtVar) > 5 ? -Math.round(ahtVar) : 0
      };
    }
  });

  return suggestions;
};
